### ISSUE TITLE
No Date Picker

### ISSUE THREAD

**Issue by bookingwp** [bookingwp/woocommerce-appointments#456]
Hello,

There's no date picker for when I have a product embedded, it was working on 4.1.8 but now it is not I already provided some details in your forum here: 

https://bookingwp.com/forums/topic/calendar-not-showing-3/

**Comment by bookingwp** [comment]
**5c1b55d0e186550b0adf5578** (2018-12-20T08:43:43.319749+00:00):

This is definitely an issue being caused by the product addon integration:

```
#!php

addons.min.js?ver=3.0.5:1 Uncaught TypeError: a(...).tipTip is not a function
    at Object.init (addons.min.js?ver=3.0.5:1)
    at HTMLFormElement.<anonymous> (addons.min.js?ver=3.0.5:1)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at HTMLDocument.<anonymous> (addons.min.js?ver=3.0.5:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
init @ addons.min.js?ver=3.0.5:1
(anonymous) @ addons.min.js?ver=3.0.5:1
each @ jquery.js?ver=1.12.4:2
each @ jquery.js?ver=1.12.4:2
(anonymous) @ addons.min.js?ver=3.0.5:1
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
```

**Comment by bookingwp** [comment]
**Željan Topić** (2018-12-20T15:07:28.905129+00:00):

sent a code snippet for this specific case to the customer.
